### ISSUE TITLE
[BUG]  Cannot Register project on AI Round

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app-alem#114]
**Describe the bug**
Register project showing as grayed out. 
**To Reproduce**
1. Go to to ai pot
2. See grayed out register proejct

**Expected behavior**
Should register project and register at same time, or let people just register from that page
**Screenshots**
<img width="410" alt="" src="https://github.com/PotLock/bos-app-alem/assets/45281667/f73682d3-ad0a-4341-ae2e-289d49f3a6d6">

**Comment by lachlanglen** [comment]
@codingshot what is the account you are viewing from?
