### ISSUE TITLE
[BUG] `404` error when clicking on an open source project's repo

### ISSUE THREAD

**Issue by thisisjoshford** [PotLock/bos-app-alem#125]
**Describe the bug**
When discovering open source projects to donate to, I encountered a `404` error on GH. Looking at the link, it appears that `github.com` is being added to the beginning of all project's repo URL. Note that the github link at the top of a profile works as expected.

**To Reproduce**
1. Go to a project's profile with a github repo listed on the bottom left of the profile (see attached gif)
2. Click on the project or hover over the link to see the incorrect url

**Expected behavior**
Opens GH repo :) 

**Screenshots**
![Rewatch GIF Recording - 2024-05-16 at 5 59 26 PM](https://github.com/PotLock/bos-app/assets/58483342/f125396c-532a-4329-ad0c-54663e2e5034)

**Comment by M-Rb3** [comment]
@thisisjoshford Thank you for reporting the issue. It has been resolved. Please test it out and let us know if you continue to experience any problems.
