### ISSUE TITLE
[BUG] Create./Dev pot not available in alpha 

### ISSUE THREAD

**Issue by 0xcrans** [PotLock/bos-app-alem#181]
**Describe the bug**
Cannot make a donation or fund the pot via alpha.potlock.io | nearian.v1.potfactory.potlock.near unavailable 
**To Reproduce**
1. Go to https://alpha.potlock.io/pot/nearian.v1.potfactory.potlock.near/projects?donateToPot=nearian.v1.potfactory.potlock.near
2. Click on donate
3. See error that no pot is available 
    - even when you choose a project manually you can see NEAR Retro Builders and MDAO pot, no feature to donate directly via create./dev pot

![image](https://github.com/user-attachments/assets/3173a0d1-34b0-4f37-9179-51fc2de975ce)

![image](https://github.com/user-attachments/assets/70cfb90b-fd9f-4401-b2af-f88a894017af)

**Comment by carina-akaia** [comment]
GM @0xcrans, I'm working on this issue. Is there any way we could attach the ticket to the `potlock-nextjs-app` repo instead of the `bos-app-alem`?

**Comment by carina-akaia** [comment]
The fix is on the way

**Comment by 0xcrans** [comment]
> GM @0xcrans, I'm working on this issue. Is there any way we could attach the ticket to the `potlock-nextjs-app` repo instead of the `bos-app-alem`?

Thank you! Closing this bug, and submitted a new one in `potlock-nextjs-app`.
https://github.com/PotLock/potlock-nextjs-app/issues/234
